version: '3.8'


services:
  nginx:
    image: "nginx:stable-alpine"
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ../project:/var/www/laravel
    depends_on:
      - php
      - mysql
      - phpmyadmin
  php:
    build: 
      context: dockerfiles
      dockerfile: php.dockerfile
    volumes:
      - ../project:/var/www/laravel  
    command: ["/bin/sh", "-c", "chown -R www-data:www-data /var/www/laravel/storage /var/www/laravel/bootstrap/cache && php-fpm"] 
  mysql: 
    image: mysql:8.0
    ports:
      - "3306:3306"
    env_file:
      - env/mysql.env
  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8090:80
    environment:
      - PMA_ARBITRARY=1   
      
 
  artisan:
    build: 
      context: dockerfiles
      dockerfile: artisan.dockerfile
    volumes:
      - ../project:/var/www/laravel  
    entrypoint: ['php','/var/www/laravel/artisan']
    restart: no


